language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database capstonedb2' -U postgres
  - psql -c "CREATE USER obinna WITH PASSWORD null;" -U postgres
  - npm run build
  - npm run create
  - 
script:
  - npm test
after_success:
  - npm run coverage
